#spring:
#  config:
#    import:
#      - classpath: /yaml/application-local.yml
#      - classpath: /yaml/logging/application-log.yml
#  profiles:
#    group:
#      logging: local, log
#    active: logging

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa